### ISSUE TITLE
数据预处理代码

### ISSUE THREAD

**Issue by cyuan031** [XinKai-Tang/ConvUNET#1]
您好，您的工作很有启发性，我希望能够复现您的代码，请问您能提供数据预处理的代码吗，感谢您的分享。

**Comment by cyuan031** [comment]
您处理过的数据集也可以，这对我非常重要，感谢您的分享。

**Comment by XinKai-Tang** [comment]
感谢你对本研究的兴趣！不大好意思，这个研究处理好的数据集之前保存在服务器上，但是服务器的前段时间损坏了，到现在也还没有修好，并且我也没有做任何灾备工作。

不过，我可以稍微讲一下预处理过程：
第一步，由于两个数据集中的图像都已经是HU形式的，故我们直接调整窗位窗宽（可调用SimplTK打开图像，用numpy.clip将CT图像值限定在[-1200, 600]；
第二步，调用Python第三方库SimpleITK提供的重采样方法对CT图像及结节掩膜进行重采样（可参考CSDN），将体素间距重采样至[1,1,1]；
第三步，调用Python第三方库LungMask分割肺实质得到的肺的掩膜（可参考CSDN），然后根据该掩膜把图像中的肺区域提取出来（可调用numpy.where来实现），剩下的非肺部区域直接赋值为-1200；
第四步，根据肺结节的中心坐标（可通过numpy.where求得）裁剪肺结节图像及其掩膜为64x64x64的分块，并将它们分别保存到新.nii.gz文件中（可通过SimpleITK写入文件）。

此外，你还可以参考CSDN关于LUNA16数据集预处理的博客、github上的其他项目（例如：NoduleNet、SGDA等）。祝好！

**Comment by XinKai-Tang** [comment]
> 您处理过的数据集也可以，这对我非常重要，感谢您的分享。

不过，我可以给你提供实验室同门处理的[LUNA16数据集](https://pan.baidu.com/s/10ZBBQYx3o9pgaqyQFf4oCQ?pwd=lung )（注意：它可能会导致实验结果与论文不符）

**Comment by cyuan031** [comment]
感谢您的分享。

**Comment by Fatima-Ito** [comment]
@ XinKai-Tang 

> > 您处理过的数据集也可以，这对我非常重要，感谢您的分享。
> 
> 不过，我可以给你提供实验室同门处理的[LUNA16数据集](https://pan.baidu.com/s/10ZBBQYx3o9pgaqyQFf4oCQ?pwd=lung)（注意：它可能会导致实验结果与论文不符）

您好，非常感谢您的工作。我是医疗图像方面的新手，请问我在下载您实验室同门处理的[LUNA16数据集](https://pan.baidu.com/s/10ZBBQYx3o9pgaqyQFf4oCQ?pwd=lung)之后，该如何开始训练，是直接python train.py吗？请问需要将该数据集保存在什么路径里，需要在哪里修改代码的相关路径呢？非常感谢🙏

**Comment by Fatima-Ito** [comment]
@XinKai-Tang 

另外，请问您能否在现在或者之后提供处理好的另外一个数据集呢？提前谢谢您的回答。

**Comment by XinKai-Tang** [comment]
@Fatima-Ito 
> 您好，非常感谢您的工作。我是医疗图像方面的新手，请问我在下载您实验室同门处理的[LUNA16数据集](https://pan.baidu.com/s/10ZBBQYx3o9pgaqyQFf4oCQ?pwd=lung)之后，该如何开始训练，是直接python train.py吗？请问需要将该数据集保存在什么路径里，需要在哪里修改代码的相关路径呢？非常感谢🙏

关于代码的运行，可以直接使用`python train.py`运行。
代码的所有超参数都保存在utils/config.py文件中，你可以根据实际情况修改。
另外，数据集的存放路径无任何要求，as you like。
不大好意思，之前处理好的所有数据集还没有找回。

**Comment by Fatima-Ito** [comment]
@XinKai-Tang 

非常感谢

**Comment by cyuan031** [comment]
@XinKai-Tang 您好，我已经成功运行了您的代码，但是我发现可能代码功能有些不完整，包括交叉训练和分割结果的保存，您能否分享一下完整代码，想学习一下您的代码思路。我的qq邮箱：1511442795@qq.com，本人承诺仅用于学习，不用于其他用途，真心的谢谢您！！！

**Comment by XinKai-Tang** [comment]
> @XinKai-Tang 您好，我已经成功运行了您的代码，但是我发现可能代码功能有些不完整，包括交叉训练和分割结果的保存，您能否分享一下完整代码，想学习一下您的代码思路。我的qq邮箱：[1511442795@qq.com](mailto:1511442795@qq.com)，本人承诺仅用于学习，不用于其他用途，真心的谢谢您！！！

@cyuan031，你下载的代码和我这里的代码是一样的，已经是完整的！
第一：完整的交叉训练代码一直都在cross_val.py文件中提供了；
第二：我也没尝试过保存三维分割结果，因为涉及到的过程太复杂了，你可以自行补充后续的工作；

**Comment by software-ai-life** [comment]
> 感谢你对本研究的兴趣！不大好意思，这个研究处理好的数据集之前保存在服务器上，但是服务器的前段时间损坏了，到现在也还没有修好，并且我也没有做任何灾备工作。
> 
> 不过，我可以稍微讲一下预处理过程： 第一步，由于两个数据集中的图像都已经是HU形式的，故我们直接调整窗位窗宽（可调用SimplTK打开图像，用numpy.clip将CT图像值限定在[-1200, 600]； 第二步，调用Python第三方库SimpleITK提供的重采样方法对CT图像及结节掩膜进行重采样（可参考CSDN），将体素间距重采样至[1,1,1]； 第三步，调用Python第三方库LungMask分割肺实质得到的肺的掩膜（可参考CSDN），然后根据该掩膜把图像中的肺区域提取出来（可调用numpy.where来实现），剩下的非肺部区域直接赋值为-1200； 第四步，根据肺结节的中心坐标（可通过numpy.where求得）裁剪肺结节图像及其掩膜为64x64x64的分块，并将它们分别保存到新.nii.gz文件中（可通过SimpleITK写入文件）。
> 
> 此外，你还可以参考CSDN关于LUNA16数据集预处理的博客、github上的其他项目（例如：NoduleNet、SGDA等）。祝好！

您好，謝謝提供預處理的流程，但還有幾個問題想請教一下
1. input 影像大小為64x64x64，進行訓練時會transform，其中一個變換是RandCrop，roi size設置64x64x64，這樣輸出不是也一樣64x64x64嗎? 想請問這樣設置的意義是什麼呢?
2. 測試的時候使用sliding_window_infer進行推論，想請問input影像大小是原始影像size，還是一樣64x64x64呢?謝謝您

**Comment by XinKai-Tang** [comment]
@yichun-hub 您好，感谢你对本研究的兴趣！
1.如果在预处理阶段已将数据裁剪为64×64×64，那么RandCrop是不会起作用的，可以删除这部分代码。代码之所以保留了这部分，是为了能适应其他未经过裁剪的数据。
2. 在测试环节中，sliding_window_infer推理结果的size和输入size会保持一致，不一定是64×64×64。

**Comment by SwimmingLiu** [comment]
您好，上述提到的LUNA16数据集已过期，请问能否重新提供一份网盘链接呢？十分感谢
> > 您处理过的数据集也可以，这对我非常重要，感谢您的分享。
> 
> 不过，我可以给你提供实验室同门处理的[LUNA16数据集](https://pan.baidu.com/s/10ZBBQYx3o9pgaqyQFf4oCQ?pwd=lung)（注意：它可能会导致实验结果与论文不符）
